### ISSUE TITLE
failing to upload the package

### ISSUE THREAD

**Issue by Nader-Issa** [OfficeDev/microsoft-teams-app-checklist#10]
Dear Team,
after creating the package successfully we are not able to upload the package, as per internal resources Azure Subscription is required but in gethub its showing Microsoft 365 subscription only, we are failing to deploy the app to customers who dont have azure subscription. also the is a strange message about storage you mention which i couldn't understand, see below

Note: Poll app is currently not supported for customers with M365 billing region as Canada, South Africa and United Arab Emirates because of data residency issues.
https://github.com/OfficeDev/microsoft-teams-app-checklist/wiki/Solution-overview#checklist-app-data-storage

Regards

**Comment by yogesh-MS** [comment]
We do not support location Canada, UAE, South Arfica due to go local policy.
