### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NicolasHumann** [OfficeDev/microsoft-teams-app-checklist#3]
Hi,

Where are really stored the data ? What is https://actions.office365.com ? Do you have documentations ?

Many thanks

**Comment by heinrich-ulbricht** [comment]
Good question, I am searching for information on this as well. The code uses the "@microsoft/m365-action-sdk". Googling for "m365-action-sdk" currently gives only 4 (!!) results. It seems to be related to [Dynamics 365 Actions](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/create-own-actions) and I'd really like to read more about this approach.

**Comment by yogesh-MS** [comment]
The data is stored at  stored in  M365 service subscription storage. Basically the App related data is stored in Azure SQL storage and other data like- images etc. stored in Azure blob storage
