### ISSUE TITLE
"error":"This service is not available in your location."

### ISSUE THREAD

**Issue by elbruno** [OfficeDev/microsoft-teams-app-checklist#6]
Hi

I'm running the step-by-step tutorial and once I run the command [npm run deploy], and login to AAD, I got the following exception:

```
Fetching zip upload url ...
API response error: {"error":"This service is not available in your location.","correlationId":"40846ac3-b508-476c-ae41-588c58462d58","serverCorrelationId":"226cb7c7-0370-4e8a-a9d5-34b156172bb7"}
Failed to get zip upload url!

```
any guidance on how to move forward from here ? 

Thanks

**Comment by yogesh-MS** [comment]
Checklist app is currently not supported for customers with M365 billing region as Canada, South Africa and United Arab Emirates because of data residency issues.

**Comment by pcox-outreach** [comment]
Has anything changed since almost a year ago when this was first raised.  I am getting the same issue still trying to test sample teams app code
