### ISSUE TITLE
Whitelisted URLS 

### ISSUE THREAD

**Issue by rhajj19** [OfficeDev/microsoft-teams-app-checklist#7]
Hello team , are there specific URLS that need to be whitelisted for this application to work ?

**Comment by yogesh-MS** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/YOKUMA~1.FAR/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/YOKUMA~1.FAR/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/YOKUMA~1.FAR/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Method | URLs
-- | --
NPM | npmjs.org    npmjs.com    actions.office365.com    login.microsoftonline.com    login.windows.net    *.blob.core.windows.net
PS1 | onegetcdn.azureedge.net    www.powershellgallery.com    psg-prod-eastus.azureedge.net    go.microsoft.com    actions.office365.com    login.microsoftonline.com    login.windows.net    *.blob.core.windows.net




</body>

</html>

**Comment by yogesh-MS** [comment]
please whitelist URLs according to above table.
